### ISSUE TITLE
tableslurp usage?

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [JeremyGrosser/tablesnap#57]
I'm having a hard time restoring more than one table at time via tableslurp. Is this possible? My tablesnap invocation is:

```
tablesnap --recursive --auto-add --backup --exclude=/snapshots/\|-tmp-\|cassandra.log --with-sse --name node-name --prefix my-prefix/ my-bucket /cassandra-data
```

When I invoke tableslurp with the "origin" argument pointing to a keyspace, I get the error `Cannot find anything to restore from my-bucket:my-prefix:/path`. If I add the table to the origin, that seems to restore fine.

I'm not sure if it's relevant, but my tablesnap-uploaded files in S3 have `-listdir.json` files only for directories with files in them--directories with only other subdirectories do not have these files.

**Comment by JeremyGrosser** [comment]
@thekad any ideas?

**Comment by thekad** [comment]
Can you paste the tableslurp invocation?

**Comment by uhoh-itsmaciek** [comment]
Sure, something that works for a single sstable from the sample schema in the datastax docs is

```
tableslurp --owner my-owner --group my-group --name backups/foo/bar my-bucket /cassandra-data/data/my-keyspace/songs-e9789df04ddf11e59b7ff5170a7d912e /restore-path
```

The credentials are in the environment. If I cut off the "origin" argument path earlier to try to get a full tablespace restore (or full node restore--is that possible?), I get the "Cannot find anything to restore..." message.

**Comment by thekad** [comment]
Hrm, I don't think that matches the usage from ``tableslurp --help``, try the following first:

    export TDEBUG=1 # for extra debugging output
    tableslurp --owner <local uid to chmod to> --group <local gid to chgrp to> --name <fqdn> <bucket name> <prefix path> <target directory>

You can try dropping the --owner and --group first then chmod it later, for simplicity. Explaining the elements:

``--name`` = the hostname you used when uploading stuff to s3, because tablesnap namespaces the backups based on the hostname, this must match whatever hostname the sstables got uploaded from
``<bucket name>`` = the name of the bucket you are restoring from
``<prefix path>`` = the path inside the namespaced directory in the bucket you want to restore from
``<target directory>`` = your local directory to download sstables to

So, if you want to restore the most recent tablesnapped backup from hostname ``gloop.work.com`` from your bucket named ``com.work.cassandra-backups`` to the target directory ``/mnt/cassandra/lib`` and the original sstables lived under ``/var/lib/cassandra`` you should use:

    tableslurp --name gloop.work.com com.work.cassandra-backups /var/lib/cassandra /mnt/cassandra/lib

the above *should* match any files in ``s3://com.work.cassandra-backups/gloop.work.com:/var/lib/cassandra``

The tool obviously needs work if the usage is convoluted, but let's try this first.

**Comment by thekad** [comment]
After taking another look... I *think* your only mistake was ``--name``

**Comment by uhoh-itsmaciek** [comment]
Thanks, but I think I actually redacted it a little too eagerly. I'm calling tablesnap with `--prefix backups/foo/ --name node-name` and tableslurp with `--name backups/foo/node-name` since as far as I can tell, tableslurp doesn't support `--prefix` (what you are calling "prefix path" above I believe  is called "origin" in the help blurb). With this, tableslurp *seems* to be looking at the right node paths (as table*snap* just prepends the prefix to the node name when determining S3 paths as far as I can tell). I definitely *can* get tableslurp to restore individual tables if I pass it a full path directly to the table data in S3 without changing anything else, and I can confirm it's hitting endpoints I expect by inspecting my bucket via the S3 console.

Incidentally, I'm using `--prefix` with tablesnap because I'm backing up multiple clusters to the same bucket, and I want to organize backups by cluster as well as by node.

I've tried to follow [the source](https://github.com/JeremyGrosser/tablesnap/blob/master/tableslurp#L124) on how restores iterate over all the relevant files, but it seems to look for `-listdir.json` files directly in the "origin" path to start with, and my tablesnap backup has none at the keyspace level or above--they only seem to show up inside directories that actually contain other files.

I've tried removing the user and group flags to simplify things as you'd suggested, but still get the same error. I've also tried `TDEBUG=1`, but there's no additional information (it does print

```console
tableslurp [2015-09-07 22:16:21,698] DEBUG Connecting to s3
tableslurp [2015-09-07 22:16:21,750] DEBUG Connected to s3
```

before it fails as before, but that's the only DEBUG-level output).

**Comment by thekad** [comment]
I see, yeah I believe the prefix support in tablesnap came after tableslurp got written, and that support hasn't been added. Anyway, yeah I believe tableslurp does require the directory you're trying to pull to have a -listdir.json file in it... Have you tried passing ``--file /some/path/to/a/sstable-listdir.json`` to tableslurp?

**Comment by uhoh-itsmaciek** [comment]
> I see, yeah I believe the prefix support in tablesnap came after tableslurp got written, and that support hasn't been added. 

Ah, got it.

> Have you tried passing --file /some/path/to/a/sstable-listdir.json to tableslurp? as per https://github.com/JeremyGrosser/tablesnap/blob/master/tableslurp#L117

I have, but I only have `-listdir.json` files in the table-level S3 directories, so I'd have to recover each table in each keyspace individually, which seems like a lot of work to orchestrate a full recovery... Am I doing something wrong in my tablesnap invocation that I don't have any tablespace-level (or above) `-listdir.json` files? Or is this a limitation of the tool? And if the latter, what's the recommended way of doing a full node restore (if any)?

**Comment by jwojcik** [comment]
I have exactly the same question.

How would one do a full restore of all column families from a point in time? I don't think that is supported at the moment.

Given a path to the keyspace and a time, tableslurp could then find in the directory below all of the json files which were created immediately prior and use those files to restore data.

Default behavior would be for time=now. The most recent json file for each column family would be used in this case.

Good work on tablesnap btw. We are excited to put it into production.

**Comment by thekad** [comment]
So the -listdir.json files store a copy of the entire contents of the directory at that point in time, meaning if you point tableslurp to a single file, it will pull all the files from said keyspace that existed at the moment that sstable got snapshotted. @uhoh-itsmaciek can you make sure the contents of your -listdir.json matches my words?

**Comment by uhoh-itsmaciek** [comment]
@thekad all (well, based on a sample) my `-listdir.json` *only* have entries for files in the same directory. Since my tablespace directories only have subdirectories in them, and no other files, the tablespace directories do not have any `-listdir.json` files at all.

**Comment by uhoh-itsmaciek** [comment]
And if I'm reading [this](https://github.com/JeremyGrosser/tablesnap/blob/master/tablesnap#L291-L296) correctly, this seems to be as intended? I believe that code is only looking in the current directory of each new SSTable file, right?

**Comment by tamsky** [comment]
I'm also confused as to the cleanest way to backup all CF using tablesnap and then restore them all using tableslurp (also unknown is the exact mechanics for loading them once slurped to disk, and getting C* to load).

Can someone outline a successful tried-and-true recipe that includes both, since tableslurp would seem to depend on how tablesnap is invoked?

I'm not sure if I should be using snapshots at all.
If I should be using snapshots, the mechanics are not clear:
   * timing of snapshot (before or after starting tablesnap) ?
   * should I use the `--backup` flag, or should I instead use `--include /<snapshot_name>/`?  both?

**Comment by jwojcik** [comment]
"Can someone outline a successful tried-and-true recipe that includes both, since tableslurp would seem to depend on how tablesnap is invoked?"

Backing up all using tablesnap is easy enough. Just give the path to the keyspace on the command line. Tablesnap will look at everything below.

As far as a full restore, you could probably just use s3cmd and copy everything back from s3 to the local machine, then run a repair on that node. I'd think cassandra would just ignore any old files that it didn't need. To clean up the old files, you would delete any files not in the most recent tableslurp created json file in the CF directory. Of course, I'd test this to see if it worked.

For snapshots - 
You should use snapshots if you would like a few days of snapshots on the filesystem. This way you won't have to go to s3 after a restore. Right now, I am not using them. 

But if you do use snapshots, remember to --exclude the snapshot and backups directories so that these don't get copied up to s3. I use:
```
--exclude \/snapshots\/|\/backups\/|-tmp$
```

So, more or less your snapshots should be ignored by tableslurp as it backs up the sstables as they are created. Since the snapshot is just a hardlink to some previously created sstable, by the time the hardlink gets created tableslurp would have already copied it to s3.

But if you do decide to use snapshots in addition to tableslurp, you need to remember to clear out the old snapshots so your don't run out of space on your filesystem.

I think the --backup flag is for when tableslurp starts - it will backup any files that are under the given path.

**Comment by tamsky** [comment]
@jwojcik thanks for [your reply](https://github.com/JeremyGrosser/tablesnap/issues/57#issuecomment-141254900)

Please correct me if I'm reading it wrong, but it seems like after a certain point in the text, opposite day begins:

> So, more or less your snapshots should be ignored by table~~slurp~~snap as it backs up the sstables as they are created. Since the snapshot is just a hardlink to some previously created sstable, by the time the hardlink gets created table~~slurp~~snap would have already copied it to s3.
>
>But if you do decide to use snapshots in addition to table~~slurp~~snap, you need to remember to clear out the old snapshots so your don't run out of space on your filesystem.
>
>I think the --backup flag is for when table~~slurp~~snap starts - it will backup any files that are under the given path.

**Comment by tamsky** [comment]
The OP's original question remains unanswered:

> I'm having a hard time restoring more than one table at time via tableslurp. Is this possible?

Can someone shed some light on it?

**Comment by uhoh-itsmaciek** [comment]
Just to follow up for the others who've joined in seeking the same answer--I'm still very much interested but I am not actively investigating this by myself right now. I can provide additional info or try out experimental patches, though.

The propsoed alternative s3cmd-based restore mechanism is clever, but it could be dramatically slower unless the purging interval is really aggressive since there will be a lot of extra (irrelevant) data to download.

**Comment by jwojcik** [comment]
I wrote it at the end of the day and must have been a bit fried. Very kind
of you to proofread and provide corrections. They all look good. Much
appreciated.

**Comment by thekad** [comment]
Fwiw I do agree this is a problem, and I had a bit of a tableslurp rewrite
going at some point, should probably dust it off.

**Comment by jwojcik** [comment]
"I'm having a hard time restoring more than one table at time via tableslurp. Is this possible?"

This does not appear to be current functionality. But with a list of tables, it is easy enough to create a bash one liner to do it.

```
ls /var/lib/cassandra/data/keyspace/ | xargs -t -I {} tableslurp -k AWS_KEY -s AWS_SECRET  bucketname /var/lib/cassandra/data/keyspace/{} /var/lib/cassandra/data/keyspace/{}
```

**Comment by thekad** [comment]
That should be correct. This is because (currently) tablesnap only uploads
-listdir.json files per sstable, so only directories with sstables  can
be... Explored? By tableslurp.

**Comment by tightly-clutched** [comment]
I can monitor and backup a whole keyspace with tablesnap using -r option. Is there any effort to make tableslurp act recursively to restore a complete backup created with tablesnap? I'm guessing it's low priority, since this issue is still open :) and I don't think it's going to be easy either now that cassandra appends UUIDs to the foldernames.

**Comment by juiceblender** [comment]
I created a PR https://github.com/JeremyGrosser/tablesnap/pull/86 though I'm not sure if you will still need it 1.5 years down...

**Comment by tightly-clutched** [comment]
I've been using datastax opscenter to backup my cluster, and it's not satisfactory. I can try tablesnap/tableslurp again on a dev cluster.
